static const FFInputFormat * const demuxer_list[] = {
    &ff_aac_demuxer,    &ff_apng_demuxer,    &ff_ass_demuxer,    &ff_flac_demuxer,
    &ff_flv_demuxer,
    &ff_h264_demuxer,
    &ff_hevc_demuxer,
    &ff_hls_demuxer,
    &ff_image2_demuxer,
    &ff_image2pipe_demuxer,
    &ff_matroska_demuxer,
    &ff_mjpeg_demuxer,
    &ff_mov_demuxer,
    &ff_mp3_demuxer,
    &ff_mpegts_demuxer,
    &ff_mpegtsraw_demuxer,
    &ff_ogg_demuxer,    &ff_rtp_demuxer,
    &ff_rtsp_demuxer,
    &ff_sdp_demuxer,
    &ff_smp_demuxer,
    &ff_srt_demuxer,
    &ff_wav_demuxer,
    &ff_webvtt_demuxer,
    &ff_image_bmp_pipe_demuxer,
    &ff_image_gif_pipe_demuxer,
    &ff_image_jpeg_pipe_demuxer,
    &ff_image_png_pipe_demuxer,
    &ff_image_tiff_pipe_demuxer,
    &ff_image_webp_pipe_demuxer,
    NULL };
