static const URLProtocol * const url_protocols[] = {
    &ff_crypto_protocol,
    &ff_data_protocol,
    &ff_ffrtmphttp_protocol,
    &ff_file_protocol,
    &ff_http_protocol,
    &ff_httpproxy_protocol,
    &ff_https_protocol,
    &ff_pipe_protocol,
    &ff_rtmp_protocol,
    &ff_rtmps_protocol,
    &ff_rtmpt_protocol,
    &ff_rtmpts_protocol,
    &ff_rtp_protocol,
    &ff_smp_protocol,
    &ff_tcp_protocol,
    &ff_tls_protocol,
    &ff_udp_protocol,
    &ff_unix_protocol,
    &ff_srt_protocol,
    NULL };
