/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "srt-native-v1-12-g38992937b2"
#endif /* AVUTIL_FFVERSION_H */
